name: Terraform CI/CD
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0  # Adjust to the version you're using
        aws_access_key_id: ${{ secrets.HARIPRIYA_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.HARIPRIYA_AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.HARIPRIYA_AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Adjust condition as needed
      run: terraform apply -auto-approve tfplan
