name: Deploy Strapi Application
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: SSH into EC2 instance and deploy Strapi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HARIPRIYA_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.HARIPRIYA_PRIVATE_SSH_KEY }}
        script: |
          cd /srv/strapi
          sudo git pull origin main
          sudo npm install  
           # Install Strapi globally
          #sudo npm install strapi@beta -g

          # Create a new Strapi project
          #strapi new priya-project --dbclient=sqlite

          # Navigate to the new project directory
          #cd priya-project

          # Start the Strapi application using pm2
          #pm2 start npm --name 'strapi' -- run develop
                   
           # Check if Strapi is already managed by pm2
          if ! sudo pm2 status | grep -q "strapi"; then
            echo "Strapi is not managed by pm2. Starting Strapi with pm2..."
             pm2 start npm --name 'strapi' -- run develop
            #sudo pm2 start "npm run start --silent" --name "strapi"
          else
            echo "Strapi is already managed by pm2. Restarting Strapi..."
            sudo pm2 restart strapi
          fi
